import type { Dog, Pound } from "@/types"

export const sampleDogs: Dog[] = [
  {
    id: 1,
    name: "Buddy",
    breed: "Labrador Retriever",
    age: "adult",
    gender: "Male",
    size: "Large",
    color: "Golden",
    location: "Mumbai, Maharashtra",
    poundId: 1,
    urgent: false,
    goodWith: ["Children", "Dogs"],
    personality: ["Friendly", "Energetic"],
    description:
      "Buddy is a loving and energetic Labrador who loves to play fetch and swim. He's great with kids and other dogs.",
    specialNeeds: false,
    energy: "high",
  },
  {
    id: 2,
    name: "Luna",
    breed: "German Shepherd",
    age: "young",
    gender: "Female",
    size: "Large",
    color: "Black",
    location: "Delhi, NCR",
    poundId: 2,
    urgent: true,
    goodWith: ["Dogs"],
    personality: ["Loyal", "Protective"],
    description:
      "Luna is a beautiful German Shepherd who is very loyal and protective. She needs an experienced owner.",
    specialNeeds: false,
    energy: "moderate",
  },
  {
    id: 3,
    name: "Charlie",
    breed: "Indian Pariah Dog",
    age: "senior",
    gender: "Male",
    size: "Medium",
    color: "Brown",
    location: "Bangalore, Karnataka",
    poundId: 3,
    urgent: false,
    goodWith: ["Children", "Cats"],
    personality: ["Calm", "Gentle"],
    description:
      "Charlie is a gentle senior Indian Pariah dog who loves to relax and enjoy quiet moments. Perfect for a calm household.",
    specialNeeds: true,
    energy: "low",
  },
  {
    id: 4,
    name: "Bella",
    breed: "Golden Retriever",
    age: "puppy",
    gender: "Female",
    size: "Large",
    color: "Golden",
    location: "Pune, Maharashtra",
    poundId: 1,
    urgent: false,
    goodWith: ["Children", "Dogs", "Cats"],
    personality: ["Playful", "Sweet"],
    description:
      "Bella is an adorable Golden Retriever puppy who loves everyone she meets. She's very social and playful.",
    specialNeeds: false,
    energy: "high",
  },
  {
    id: 5,
    name: "Max",
    breed: "Beagle",
    age: "adult",
    gender: "Male",
    size: "Medium",
    color: "Brown",
    location: "Chennai, Tamil Nadu",
    poundId: 2,
    urgent: false,
    goodWith: ["Children"],
    personality: ["Curious", "Friendly"],
    description:
      "Max is a curious Beagle who loves to explore and follow scents. He's great with children and very friendly.",
    specialNeeds: false,
    energy: "moderate",
  },
  {
    id: 6,
    name: "Daisy",
    breed: "Mixed Breed",
    age: "young",
    gender: "Female",
    size: "Small",
    color: "Mixed",
    location: "Kolkata, West Bengal",
    poundId: 3,
    urgent: true,
    goodWith: ["Dogs"],
    personality: ["Shy", "Sweet"],
    description: "Daisy is a sweet mixed breed who is a bit shy at first but warms up quickly. She loves other dogs.",
    specialNeeds: false,
    energy: "moderate",
  },
  {
    id: 7,
    name: "Rocky",
    breed: "Indian Pariah Dog",
    age: "adult",
    gender: "Male",
    size: "Medium",
    color: "Black",
    location: "Hyderabad, Telangana",
    poundId: 4,
    urgent: false,
    goodWith: ["Children", "Dogs"],
    personality: ["Loyal", "Brave"],
    description: "Rocky is a brave and loyal Indian Pariah dog who makes an excellent guard dog and family companion.",
    specialNeeds: false,
    energy: "moderate",
  },
  {
    id: 8,
    name: "Priya",
    breed: "Spitz",
    age: "young",
    gender: "Female",
    size: "Small",
    color: "White",
    location: "Jaipur, Rajasthan",
    poundId: 5,
    urgent: false,
    goodWith: ["Children", "Cats"],
    personality: ["Playful", "Alert"],
    description: "Priya is a beautiful white Spitz who is very alert and playful. She's perfect for apartment living.",
    specialNeeds: false,
    energy: "moderate",
  },
]

export const samplePounds: Pound[] = [
  {
    id: 1,
    name: "Mumbai Animal Welfare Society",
    address: "Bandra West, Mumbai, Maharashtra 400050",
    phone: "+91 98765 43210",
    lat: 19.076,
    lng: 72.8777,
    availableDogs: 45,
    hours: "Mon-Sun 9am-6pm",
    type: "rescue",
  },
  {
    id: 2,
    name: "Delhi Animal Care Center",
    address: "Lajpat Nagar, New Delhi, Delhi 110024",
    phone: "+91 98765 43211",
    lat: 28.6139,
    lng: 77.209,
    availableDogs: 32,
    hours: "Mon-Sun 10am-7pm",
    type: "municipal",
  },
  {
    id: 3,
    name: "Bangalore Dog Rescue",
    address: "Koramangala, Bangalore, Karnataka 560034",
    phone: "+91 98765 43212",
    lat: 12.9716,
    lng: 77.5946,
    availableDogs: 28,
    hours: "Tue-Sun 9am-5pm",
    type: "shelter",
  },
  {
    id: 4,
    name: "Hyderabad Pet Shelter",
    address: "Banjara Hills, Hyderabad, Telangana 500034",
    phone: "+91 98765 43213",
    lat: 17.385,
    lng: 78.4867,
    availableDogs: 22,
    hours: "Mon-Sat 10am-6pm",
    type: "shelter",
  },
  {
    id: 5,
    name: "Jaipur Animal Rescue",
    address: "C-Scheme, Jaipur, Rajasthan 302001",
    phone: "+91 98765 43214",
    lat: 26.9124,
    lng: 75.7873,
    availableDogs: 18,
    hours: "Mon-Sun 8am-6pm",
    type: "rescue",
  },
]
